[tool.poetry]
name = "keyweave"
version = "0.18.6"
description = "Framework for defining global hotkeys."
authors = ["GregRos <gregros@gregros.dev>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/GregRos/keyweave"
[[tool.poetry.include]]
path = "keyweave/"

[[tool.poetry.include]]
path = "README.md"

[[tool.poetry.include]]
path = "LICENSE.md"

# Ship the PEP 561 marker in the WHEEL
[[tool.poetry.include]]
path = "keyweave/py.typed"
format = "wheel"


[tool.poetry.dependencies]
python = ">=3.13,<3.15"
keyboard = "^0.13.5"
pywin32 = { version = "^311", markers = "sys_platform == 'win32'" }
mouse = { version = "^0.7.1", markers = "sys_platform != 'win32'" }
pyyaml = "^6.0.3"
termcolor = "^3.1.0"
python-baseconv = "^1.2.2"
pyee = "^13.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.pyright]
typeCheckingMode = "strict"
autoImportCompletions = true
autoIndent = true
diagnosticMode = "workspace"
reportUnusedImport = false
ignore = [
    "**/Lib/*.py",
    "**/site-packages/**",
    "**/.venv/**/*",
    "**/dist/**/*",
    "**/.vscode*/**/*",
    "**/*.pyi",
]
exclude = ["**/site-packages/**", "**/.venv/**/*", "**/dist/**/*", "**/*.pyi"]
[tool.black]
line-length = 80
[tool.poetry.group.dev.dependencies]
pyright = ">=1.1.406,<2.0.0"
black = ">=25.9.0,<26.0.0"
mouse = ">=0.7.1,<0.8.0"
