[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skip_gram"
version = "0.1.2"
description = "Skip-Gram Word2Vec model with Hierarchical Softmax in PyTorch"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Krishna Simha", email = "krishna2005simha@gmail.com"}
]
dependencies = [
    "torch>=2.0",
    "nltk>=3.8",
    "numpy>=1.24"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
keywords = ["word2vec", "skip-gram", "hierarchical-softmax", "NLP", "PyTorch"]
