[project]
name = "codepeek"
version = "2.0.1"
description = "Extract and analyze codebases from GitHub or local directories using AI (SOLID, Design Patterns, Security, Architecture)"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Ahmed Abd Alzeez", email = "ahmedabdalziz.1886@gmail.com" }
]
dependencies = [
    "requests",
    "tqdm",
    "reportlab",
    "python-dotenv"
]

[project.scripts]
codepeek = "codepeek.cli:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
