[project]
name = "overleaf-mcp"
version = "0.1.4"
description = "MCP server for Overleaf projects"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.17.0",
    "python-dotenv>=1.1.1",
]

[project.scripts]
overleaf-mcp = "overleaf_mcp.__main__:main"
