[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "orrery"
dynamic = ["version"]
description = 'A framework for supporting MVC and observer patterns in Python'
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = []
authors = [
  { name = "Tom Doel", email = "tom.doel@codechoreography.co.uk" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
]

[project.urls]
Documentation = "https://github.com/CodeChoreography/orrery#readme"
Issues = "https://github.com/CodeChoreography/orrery/issues"
Source = "https://github.com/CodeChoreography/orrery"

[tool.hatch.version]
source = "vcs"

[project.optional-dependencies]
tests = ["pytest"]
lint = [
  "pylint"
]

[tool.pytest.ini_options]
pythonpath = [
  "src",
]

[tool.pylint.main]
source-roots = "src"

[tool.pylint.'MESSAGES CONTROL']
disable=[
  'no-else-return',
  'no-else-raise',
  'too-many-arguments',
  'too-many-positional-arguments',
  'too-few-public-methods',
  'too-many-public-methods',
  'no-name-in-module',
  'too-many-function-args'
]