[project]
name = "navdict"
version = "0.6.1"
description = "A navigable dictionary with dot notation access and automatic file loading"
readme = "README.md"
authors = [
    {name = "IvS KU Leuven"}
]
maintainers = [
    {name = "Rik Huygen", email = "rik.huygen@kuleuven.be"},
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "rich>=14.0.0",
    "ruamel-yaml>=0.18.12",
]


[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "setuptools", # needed by PyCharm
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material",
    "mkdocs-autorefs",
]
lint = [
    "ruff>=0.12.8",
]

[project.entry-points."navdict.directive"]
yaml = 'navdict.directives:load_yaml'
csv = 'navdict.directives:load_csv'
env = 'navdict.directives:env_var'

[tool.uv]
default-groups = ["dev", "docs"]

[tool.pytest.ini_options]
pythonpath = [
    "src",
]
testpaths = [
    "tests",
]
addopts = "-ra --cov --cov-branch --cov-report html"
log_capture = true
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "[%(asctime)s] %(threadName)-12s %(levelname)-8s %(name)-12s %(lineno)5d:%(funcName)-15s:%(module)-15s %(message)s"
filterwarnings = [
    "ignore::DeprecationWarning"
]

[tool.ruff]
line-length = 120

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
