[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "birdbrain-python-library-2"
version = "0.9.17"
license = "LGPL-3.0-only"
description = "Rewritten Python Library for Birdbrain Technologies Hummingbird Bit and Finch 2."
readme = "README.rst"
authors = [ { name = "Frank Morton", email = "fmorton@base2inc.com" } ]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/fmorton/BirdBrain-Python-Library-2"
Issues = "https://github.com/fmorton/BirdBrain-Python-Library-2/issues"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
]

[tool.hatch.build]
packages = ["src/birdbrain_python_library_2"]

[tool.black]
line-length = 140
target-version = ["py37"]
skip-string-normalization = true

[tool.pytest.ini_options]
testpaths = ["tests"]