[project]
name = "gpe-tokenizer"
version = "0.1.0"
description = "Grapheme Pair Encoding Tokenizer for Sinhala Language"
authors = [
    {name = "Schizo00",email = "naween.k@live.com"}
]
readme = "README.md"
requires-python = ">=3.13, <3.15"
dependencies = [
    "datasets (>=4.2.0,<5.0.0)",
    "huggingface-hub (>=0.35.3,<0.36.0)",
    "grapheme (>=0.6.0,<0.7.0)",
    "regex (>=2025.9.18,<2026.0.0)",
    "tokenizers (>=0.22.1)",
    "joblib (>=1.5.2,<2.0.0)",
    "transformers (>=4.57.1,<5.0.0)",
    "torch (>=2.9.0,<3.0.0)",
    "accelerate (>=1.10.1,<2.0.0)",
    "twine (>=6.2.0,<7.0.0)"
]

[tool.poetry]
packages = [{ include = "gpe_tokenizer", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[dependency-groups]
dev = [
    "ipykernel (>=7.0.1,<8.0.0)"
]
