[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "nest-zc"   # distribution name on (Test)PyPI â€” can have hyphens
version = "0.1.1"
description = "Example"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [{name="You", email="you@example.com"}]

[tool.hatch.build.targets.wheel]
packages = ["src/nest"]     # path to your import package directory