[project]
name = "flowerpower-io"
version = "0.1.6.3"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "legout", email = "ligno.blades@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "fsspec-utils[full]>=0.1.5",
    "adbc-driver-manager>=1.4.0",
    "aiosqlite>=0.21.0",
    "datafusion>=43.1.0",
    "deltalake>=0.24.0",
    "duckdb>=1.1.3",
    "orjson>=3.10.12",
    "pandas>=2.2.3",
    "polars>=1.15.0",
    'pyarrow>=18.1.0',
    'pydala2>=0.9.4.5',
    "redis>=5.2.1",
    "sherlock>=0.4.1",
    "sqlalchemy>=2.0.30",
    "msgspec>=0.19.0",
]
[project.urls]
homepage = "https://legout.readthedocs.io/flowerpower-io"
repository = "https://github.com/legout/flowerpower-io"

[project.optional-dependencies]
legacy = ["polars-lts-cpu>=1.32.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/flowerpower_io"]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipython>=9.4.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.17",
    "nbformat>=5.10.4",
    "quarto>=0.1.0",
]
