[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "retinalysis-inference"
version = "0.4.0"
description = "Retinal model inference package"
authors = [{ name = "Jose Vargas", email = "j.vargasquiros@erasmusmc.nl" }]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10, <3.13"
dependencies = [
    "numpy == 2.*",
    "pandas == 2.*",
    "opencv-python == 4.*",
    "joblib==1.*",
    "Pillow == 11.*",
    "click==8.*",
    "pydicom==3.*",
    "nbstripout==0.3.9",
    "lightning==2.1.0",
    "albumentations==1.3.1",
    "PyYAML>=5.4",
    "monai==1.5.0",
    "huggingface-hub==0.25.1",
    "GPUtil==1.*"
]

[tool.setuptools.packages.find]
include = ["rtnls_inference*"]

[project.urls]
"Homepage" = "https://github.com/Eyened/retinalysis-inference"
"Bug Tracker" = "https://github.com/Eyened/retinalysis-inference/issues"