[project]
name = "odoo-tools-grap"
version = "1.3.3"
description = "Small CLI tool for Odoo"
authors = [
  {name = "Sylvain LE GAL", email = "sylvain.legal@grap.coop"},
]
maintainers = [
  {name = "Sylvain LE GAL", email = "sylvain.legal@grap.coop"},
]
readme = "README.md"
license = "AGPLv3+"
repository = "https://gitlab.com/grap-rhone-alpes/odoo-tools-grap"
keywords = ["cli", "odoo", "GRAP"]
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Intended Audience :: Developers",
    "Development Status :: 4 - Beta",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Framework :: Odoo",
]

requires-python = ">=3.9,<4.0"
dependencies = [
  "click",
  "click-loglevel",
  "git-aggregator",
  "GitPython",
  "PyGithub",
  "loguru",
  "plumbum",
  "single-source",
]


[project.urls]
Repository = "https://gitlab.com/grap-rhone-alpes/odoo-tools-grap"

[project.scripts]
oow = "odoo_tools_grap.cli.cli:main"
odoo-openupgrade-wizard = "odoo_tools_grap.cli.cli:main"


[tool.poetry.group.dev.dependencies]
pylint = "*"
tox = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
