[tool.poetry]
name = "quantfox-common"
version = "0.1.15"
description = "QuantFox common utilities: domain (market/finance/ds) + adapters (db/s3/redis/dss)"
authors = ["QuantFox <dev@quantfox.com>"]
readme = "README.md"
packages = [{ include = "qf_common", from = "src" }]

[tool.setuptools.package-data]
qf_common = ["py.typed"]

[tool.poetry.dependencies]
python = ">=3.12"
ruff = "^0.7.0"
numpy = "^2.1.1"
pandas = "^2.2.3"
scipy = "^1.13"
pydantic = "^2.8"
boto3 = "^1.34"
psycopg2-binary = "^2.9.10"
redis = "^5.0.8"
sqlalchemy = "^2.0.36"
requests = "^2.32.3"
matplotlib = "^3.9.2"
statsmodels = "^0.14.3"
scikit-learn = "^1.5.1"
beautifulsoup4 = "^4.12.3"
openpyxl = "^3.1.5"
jupyter = "^1.1.1"
notebook = "^7.4.7"
minio = "7.2.14"
cloudpickle = "^3.1.1"
psutil = "^5.9.8"

[tool.poetry.group.dev.dependencies]
watchdog = "*"
black = "^24.8.0"
flake8 = "^7.1.1"
pytest = "^8.3.3"
ipykernel = "^6.29.5"
pylint = "^3.1.0"
astroid = "^3.1.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

