[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[project]
name = "aiattribution"
version = "0.1.0"
description = "A Python utility for creating and interpreting AI Attribution statements"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Martin PrpiÄ", email = "mprpic@redhat.com" }
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.3.0",
    "questionary>=2.1.1",
]

[project.urls]
Homepage = "https://github.com/mprpic/aiattribution"
Repository = "https://github.com/mprpic/aiattribution"

[project.scripts]
aia = "aiattribution.cli:cli"

[dependency-groups]
test = [
    "pytest>=8.4.2",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
select = ["F", "E", "W", "I", "N"]

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
warn_unused_ignores = true
