[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kuroboros"
version = "1.0.6"
description = "A kubernetes operator framework"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    { name = "Juan Edwards" }
]
dependencies = [
    "click==8.2.0",
    "kubernetes==32.0.1",
    "inflect==7.5.0",
    "jinja2==3.1.6",
    "prometheus-client==0.21.1",
    "falcon==4.0.2",
    "gunicorn==23.0.0",
    "jsonpatch==1.33",
    "case-converter==1.2.0",
    "tomlkit==0.13.3"
]

[project.scripts]
kuroboros = "kuroboros.cli.main:cli"

[tool.setuptools.packages.find]
include = ["kuroboros*"]

[tool.setuptools.package-data]
"kuroboros" = ["cli/templates/*", "cli/templates/**/*"]

[tool.setuptools]
include-package-data = true

[project.urls]
"Homepage" = "https://github.com/jedwards94/kuroboros"
