[project]
name = "duckdi"
version = "0.1.13"
description = "ðŸ¦† A minimal dependency injection library for Python"
authors = [{ name = "Phe Pato", email = "pheprogrammer@gmail.com" }]
readme = "README.md"
license = "MIT"

[project.urls]
homepage = "https://pypi.org/project/duckdi/"
repository = "https://github.com/PheFreire/DuckDI"

[tool.poetry]
packages = [{include = "duckdi", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10"
toml = ">=0.10.2,<0.11.0"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.2.0"
bandit = "^1.8.3"
mypy = "^1.15.0"
pytest = "^8.3.5"

[tool.pytest.ini_options]
pythonpath = ["tests"]
log_cli = true

[tool.poetry.scripts]
duckdi = "duckdi.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
