[tool.poetry]
name = "novas3d"
version = "0.1.10"
description = ""
authors = ["Matthew Rozak <matthew.rozak@mail.utoronto.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.13"
monai = ">=0.8.0, <=0.9.0"
torch = "<2.0.0"
matplotlib = "3.4.2"
nibabel = "3.2.1"
numpy = "<2.0.0"
scikit-image = "<0.22.0"
antspyx = "*"
tifffile = "2021.11.2"
tqdm = "^4.66.5"
connected-components-3d = "*"
vg = "2.0.0"
pytransform3d = "2.1.0"
scipy = "*"
networkx = "2.6.3"
ignite = "1.1.0"
pytorch-ignite = "*"
sknw = "*"
scikit-learn = "*"
einops = "0.3.2"
jupyter = '*'
notebook = '*'
imageio = '2.28.0'
pyparsing = '3.1.0'
anyio = '4.5.0'
ipython = '7.34.0'
jsonschema-specifications = '2023.3.6'
typing-extensions = '>=4.1'



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
