[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "local-flight-map"
version = "1.1.8"
description = "Open Air Traffic map based on ADS-B Exchange and Open Sky Data."
requires-python = ">=3.12"
authors = [
    { name="Dawid Ciepiela", email="71898979+sarumaj@users.noreply.github.com" }
]
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "aiohttp==3.12.15",
    "asyncio==4.0.0",
    "async-lru==2.0.5",
    "fastapi==0.118.0",
    "folium==0.20.0",
    "itsdangerous==2.2.0",
    "nest-asyncio==1.6.0",
    "orjson==3.11.3",
    "pydantic==2.11.9",
    "pydantic-settings==2.11.0",
    "uvicorn==0.37.0"
]

[project.scripts]
local-flight-map = "local_flight_map.__main__:main"

[project.optional-dependencies]
test = [
    "pytest==8.4.2",
    "pytest-asyncio==1.2.0"
]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]

[tool.setuptools.package-data]
"local_flight_map.ui.app" = [
    "static/*",
    "static/**/*",
    "interface.js"
]
"local_flight_map.ui.plugins" = [
    "js/*.js"
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = [
    "-v",
    "--asyncio-mode=auto"
]
