[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-server-svn"
version = "0.1.4.post2"
description = "An MCP server integration for SVN"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Manav Desai", email = "manav27202@gmail.com" }]
dependencies = ["fastmcp"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.scripts]
mcp-server-svn = "mcp_server_svn.mcp_server_svn:main"