[project]
name = "yaxai"
version = "0.14.0"
description = ""
authors = [
    {name = "Henryk Konsek",email = "hekonsek@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0",
    "typer>=0.12.3",
    "pydantic (>=2.12.2,<3.0.0)",
]

[project.scripts]
yax = "yaxai.cli:app"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
check-depz = "^0.18.0"
pytest-cov = ">=5.0.0"
pytest-xdist = "^3.6.1"

[tool.pytest.ini_options]
addopts = ["-n=4", "--cov=yaxai", "--cov-report=term-missing", "--cov-fail-under=50"]
testpaths = ["tests"]
