[build-system]
requires = ["flit_core"]
build-backend = "flit_core.buildapi"

[project]
name = "gguf-backend"
authors = [{name = "calcuis", email = "info@calcu.io"}]
description = "backend api"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/calcuis/simple-image-generator-frontend"