[build-system]
requires = ["setuptools>=61", "wheel"] 
build-backend = "setuptools.build_meta"

[project]
name = "osm-integration-haystack"
version = '0.1.11'
description = "A Haystack component integrating Overpass API for OpenStreetMap"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    {name = "Wyatt \"Huaye\" Wei", email = "h.w_wyatt@protonmail.com"},
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",  
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://github.com/grexrr/osm-integration-haystack"

[tool.setuptools.packages.find]
where = ["src"]
include = ["osm_integration_haystack*"] 

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}