[project]
name = "taskanalytics-data-wrapper"
version = "0.3.0"
description = "a wrapper for using Task Analytics APIs and downloading survey responses"
authors = [
    {name = "Tobias McVey", email = "tobias.mcvey@nav.no"},
]
readme = "README.md"
requires-python = ">=3.10"
keywords = ["Task Analytics", "Top Tasks"]
license = {file = "LICENSE"}

dependencies = [
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.4",
]

[project.urls]
"Homepage" = "https://github.com/navikt/taskanalytics-data-wrapper"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
