[project]
name = "iterwrap"
version = "0.4.6.post1"
authors = [
  { name="starreeze", email="starreeze@foxmail.com" },
]
description = "Wrapper on iterable for automatic caching, resuming, retrying, and multiprocessing"
readme = "readme.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
  'tqdm',
  'multiprocess',
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"