[project]
name = "promplate-trace"
version = "0.3.0dev6"
description = "Observability for Promplate"
authors = [
    { name = "Muspi Merol", email = "me@promplate.dev" },
]
dependencies = [
    "promplate>=0.3.0rc3,<0.5",
    "pydantic-settings>=2,<3",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.optional-dependencies]
langsmith = [
    "langsmith~=0.1",
]
langfuse = [
    "langfuse~=3.0",
]

[project.urls]
homepage = "https://promplate.dev/py"
repository = "https://github.com/promplate/trace"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "isort>=5.12.0",
    "black>=23.11.0",
]

[tool.pdm.scripts.fmt]
composite = [
    "isort ./{args}",
    "black ./{args}",
]

[tool.isort]
line_length = 200

[tool.black]
line-length = 160

[tool.pyright]
typeCheckingMode = "standard"
