[project]
name = "sinapsis-object-detection"
version = "0.4.0"
description = "Mono repo with packages for inference and training with object detection models"
authors = [
    {name = "SinapsisAI", email = "dev@sinapsis.tech"},
]
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "sinapsis>=0.1.1",
]

[[tool.uv.index]]
url = "https://pypi.sinapsis.tech/"


[dependency-groups]
dev = [
    "ruff>=0.8.3",
    "pre-commit>=4.0.1",
]

[project.optional-dependencies]
all = [
    "sinapsis-dfine[all]",
    "sinapsis-object-detection[gradio-app]",
    "sinapsis-rfdetr[all]",
    "sinapsis-ultralytics[all]",
]
gradio-app = [
    "sinapsis[webapp]>=0.2.2",
]

[tool.ruff]
lint.select = [
    "ARG",
    "ANN",
    "BLE",
    "C4",
    "D",
    "E",
    "F",
    "FIX",
    "FLY",
    "I",
    "PERF",
    "PIE",
    "PLR6301",
    "RUF",
    "RSE",
    "SIM",
    "SLOT",
    "T10",
    "T20",
    "TD",
    "TID",
]
lint.preview = true
lint.pydocstyle.convention = "google"
lint.ignore = [
    "ANN401",
    "D100",
    "D104",
    "D107"
]
line-length = 120
show-fixes = true

[[tool.uv.index]]
name = "sinapsis"
url = "https://pypi.sinapsis.tech/"


[tool.uv.workspace]
members = ["packages/*"]
exclude = ["packages/*.egg-info"]

[tool.setuptools]
packages = { find = { where = ["packages"] } }


[tool.uv.sources]
sinapsis-rfdetr = { workspace = true }
sinapsis-dfine = { workspace = true }
sinapsis-ultralytics = { workspace = true }
sinapsis-object-detection = { workspace = true }


[project.urls]
Homepage = "https://sinapsis.tech"
Documentation = "https://docs.sinapsis.tech/docs"
Tutorials = "https://docs.sinapsis.tech/tutorials"
Repository = "https://github.com/Sinapsis-AI/sinapsis-object-detection.git"
