[tool.poetry]
authors = ["Alex Basile <basileaw@gmail.com>"]
description = "Serve Python CLI applications in the browser using ttyd"
license = "MIT"
name = "terminaide"
packages = [{ include = "terminaide" }, { include = "terminarcade" }]
readme = "README.md"
repository = "https://github.com/basileaw/terminaide"
version = "1.4.5"

[tool.poetry.dependencies]
bs4 = "^0.0.2"
h11 = "^0.16.0"
httpcore = "^1.0.9"
httpx = "^0.28.1"
jinja2 = "^3.1.2"
pydantic = "^2.4.2"
python = ">=3.12,<4.0"
readchar = "^4.2.1"
rich = "^14.0.0"
websockets = "^12.0"
fastapi = "^0.117"
uvicorn = "^0.34.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
pytest-timeout = "^2.4.0"
requests = "^2.32.0"
poethepoet = "^0.37.0"
toolbox = { git = "https://github.com/basileaw/toolbox.git" }

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poe]
include = ["tasks.yaml"]
