[project]
name = "sycommon-python-lib"
version = "0.1.25"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aio-pika>=9.5.7",
    "aiohttp>=3.12.15",
    "decorator>=5.2.1",
    "fastapi>=0.118.0",
    "kafka-python>=2.2.15",
    "loguru>=0.7.3",
    "mysql-connector-python>=9.4.0",
    "nacos-sdk-python>=2.0.9",
    "pydantic>=2.11.9",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.43",
    "starlette>=0.46.2",
    "uuid>=1.30",
    "uvicorn>=0.37.0",
]

[tool.setuptools]
packages = {find = {where = ["src"]}}

[project.scripts]
sycommon = "command.cli:main"
