[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "summarizedpy"
version = "0.1.0.post1"
description = "A differential expression analysis package for proteomics data, which leverages transcriptomics tools."
readme = "README.md"
authors = [
  {name = "Sebastian Dohm-Hansen", email = "heinrich.sebastian.dohmhansen@gmail.com"}
]
maintainers = [
  {name = "Sebastian Dohm-Hansen", email = "heinrich.sebastian.dohmhansen@gmail.com"}
]

license = {text = "MIT"}
requires-python = ">= 3.9"

dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "pyarrow",
    "adjustText",
    "pyjanitor",
    "openpyxl"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"depy" = ["/R/*.R"]

[project.optional-dependencies]
dev = ["jupyter", "pytest"]
