[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agton"
version = "0.2.1"
description = "TON Blockchain SDK"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
  { name = "Alexey Gosunov", email="agosunov@gmail.com" },
]
dependencies = [
  "PyNaCl>=1.5.0",
  "bitarray>=3.0.0",
  "requests>=2.32.3",
]

[project.optional-dependencies]
wallet = ["agton-wallet>=0.2.1"]
jetton = ["agton-jetton>=0.2.1"]
dedust = ["agton-dedust>=0.2.1"]
all = [
  "agton-wallet>=0.2.1",
  "agton-jetton>=0.2.1",
  "agton-dedust>=0.2.1",
]

[tool.setuptools.packages.find]
include = ["agton.ton*"]
namespaces = true

[project.urls]
Homepage = "https://github.com/gosunov/agton"
