[project]
name = "bitwarden-rest-client"
version = "0.1.3"
description = "A rest client for the Bitwarden Cli API"
readme = "README.md"
requires-python = ">=3.14"
authors = [
    {name = "Kalle M. Aagaard", email = "git@k-moeller.dk"},
]
maintainers = [
    {name = "Kalle M. Aagaard", email = "git@k-moeller.dk"},
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.12.2",
]

[project.urls]
Homepage = "https://github.com/KalleDK/py-bitwarden-rest-client"
Documentation = "https://github.com/KalleDK/py-bitwarden-rest-client"
Repository = "https://github.com/KalleDK/py-bitwarden-rest-client.git"

[project.optional-dependencies]
cli = [
    "rich>=14.2.0",
    "typer>=0.19.2",
]

[dependency-groups]
test = [
    "pytest>=8.4.2",
]
stubs = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/bitwarden_rest_client"]

[tool.pyright]
include = ["src", "tests", "examples"]
typeCheckingMode = "strict"
exclude = ["**/__pycache__"]
pythonVersion = "3.14"

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.unasyncd]
files = { "src/bitwarden_rest_client/_async" = "src/bitwarden_rest_client/_sync"}

[tool.unasyncd.add_replacements]
AsyncBitwardenClient = "BitwardenClient"
"httpx.AsyncClient" = "httpx.Client"
"aclose" = "close"
