[project]
name = "planqk-quantum"
version = "2.23.0"
description = "SDK to interact with PLANQK quantum backends."
authors = [
    { name = "Kipu Quantum GmbH", email = "info@kipu-quantum.com" },
]
maintainers = [
    { name = "Sebastian Wagner", email = "sebastian.wagner@kipu-quantum.com" },
    { name = "Michael Wurster", email = "michael.wurster@kipu-quantum.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.5.0,<2.10",
    "qiskit==1.4.3",
    "qiskit-braket-provider==0.4.6",
    "qiskit-ibm-runtime==0.41.1",
    "qiskit-ionq==0.5.13",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[project.urls]
Homepage = "https://kipu-quantum.com/platform"
Documentation = "https://docs.planqk.de"
Repository = "https://gitlab.com/planqk-foss/planqk-quantum"
Issues = "https://gitlab.com/planqk-foss/planqk-quantum/-/issues"
Changelog = "https://gitlab.com/planqk-foss/planqk-quantum/-/blob/main/CHANGELOG.md"

[build-system]
requires = ["setuptools >= 61.0", "wheel", "twine"]
build-backend = "setuptools.build_meta"

# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
[tool.setuptools.packages.find]
include = ["planqk*"]
