[tool.isort]
profile = "black"

[build-system]
requires = ["hatchling", "hatch-build-scripts", "ruff", "betterproto2_compiler","grpcio-tools"]
build-backend = "hatchling.build"

[tool.uv.extra-build-dependencies]
betterosi = [{requirement = "betterproto2_compiler", match-runtime=true}]
omega-prime-trajdata = [{requirement = "betterproto2_compiler", match-runtime=true}]

[[tool.hatch.build.hooks.build-scripts.scripts]]
commands = [
    "python gen_protos.py"
]

[project]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
]
name = "omega-prime-trajdata"

version = "1.4.1.4"
authors = [{ name = "Michael Schuldes", email = "michael.schuldes@rwth-aachen.de" }]
description = "A fork of trajdata using betterproto2 and including a converter to omega-prime"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0",
    "tqdm>=4.62",
    "matplotlib>=3.5",
    "dill>=0.3.4",
    "pandas>=1.4.1",
    "pyarrow>=7.0.0",
    "torch>=1.10.2",
    "zarr>=2.11.0",
    "kornia>=0.6.4",
    "seaborn>=0.12",
    "bokeh>=3.0.3",
    "geopandas>=0.13.2",
    "scipy>=1.9.0",
    "opencv-python>=4.5.0",
    "shapely>=2.0.0",
    "betterproto2 (>=0.8,<1)",
    "betterproto2_compiler",
    "omega-prime>=0.1.19"
]

[project.optional-dependencies]
av2 = ["av2==0.2.1"]
dev = ["black", "isort", "pytest", "pytest-xdist", "twine", "build"]
interaction = ["lanelet2"]
#lyft = ["l5kit==1.5.0"]
#nusc = ["nuscenes-devkit>=1.2.0"]
waymo = ["tensorflow>=2.19.0", "intervaltree"]
vod = ["vod-devkit==1.1.2"]

[project.urls]
"Homepage" = "https://github.com/nvr-avg/trajdata"
"Bug Tracker" = "https://github.com/nvr-avg/trajdata/issues"


[project.entry-points.'omega_prime.plugins.converter']
from-trajdata = 'trajdata:TrajdataConverter'

[tool.hatch.build.targets.wheel]
# Map the actual package name to the source directory
packages = [
    "src/trajdata"
]