[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "makeitsample"
version = "1.0.1"
description = "A Toolkit for Generating Typological Language Samples Based on the Diversity Value"
authors = [
  { name="Luca Brigada Villa", email="luca.brigadavilla@unipv.it" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.7"
dependencies = [
  "pandas",
  "networkx"
]
keywords = [
  "linguistics",
  "typology",
  "language diversity",
  "language sampling",
  "diversity value",
  "language families",
  "phylogenetics",
  "sampling"
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/unipv-larl/makeitsample"
Issues = "https://github.com/unipv-larl/makeitsample/issues"

[project.scripts]
makeitsample = "makeitsample.makeitsample:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["makeitsample"]
