[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "orcaagent-cli"
dynamic = ["version"]
description = "CLI for interacting with orcaagent API"
authors = []
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ['LICENSE']
dependencies = [
    "click>=8.1.7",
    "pydantic>=2.7.4,<3.0.0",
    "langchain>=0.3.27,<2.0.0",          
    "langchain-core>=0.3.76,<1.0.0",
    "langchain-community>=0.3.29",       
    "langgraph>=0.4.0",
    "langsmith>=0.3.45",
    "langgraph-sdk>=0.1.0 ; python_version >= '3.11'",
    "python-dotenv>=1.0.0",
    "typing-extensions>=4.10,<5",
    "requests>=2.0,<3",
    "rich>=13.9.4",
    "aiohttp>=3.8.3,<4.0.0",
    "langgraph-api==0.4.28",
                
]
[tool.hatch.version]
path = "orcaagent_cli/__init__.py"
[project.optional-dependencies]
inmem = [
    "langgraph-api==0.4.28 ; python_version >= '3.11'",
    "langgraph-runtime-inmem>=0.7 ; python_version >= '3.11'",
    "python-dotenv>=0.8.0",
]

[project.urls]
Repository = "https://git.woa.com/OrcaAgent/OrcaAgent-Cli"

[project.scripts]
orcaagent = "orcaagent_cli.cli:cli"

[dependency-groups]
dev = [
    "ruff",
    "codespell",
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "pytest-watch",
    "mypy",
    "msgspec",
]

[tool.uv]
default-groups = ['dev']

[tool.hatch.build.targets.wheel]
packages = ["orcaagent_cli", "sdk_py", "schemas"]

[tool.pytest.ini_options]
addopts = "--strict-markers --strict-config --durations=5 -vv"
asyncio_mode = "auto"

[tool.ruff]
lint.select = [
  "E",  # pycodestyle
  "F",  # Pyflakes
  "UP", # pyupgrade
  "B",  # flake8-bugbear
  "I",  # isort
]
lint.ignore = ["E501", "B008"]
