[project]
name = "RubigramClient"
version = "1.7.2"
description = "A simple and flexible Python library for building advanced Rubika bots with powerful message handling, inline buttons, and custom filters."
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
  { name="Javad", email="MrJavad.Email@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aiohttp",
    "aiofiles"
]

urls = { "Homepage" = "https://github.com/Javad-RZ/rubigram" }