[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyshareit"
version = "1.10.0"
description = "A fast, peer-to-peer file sharing tool with a simple terminal interface."
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
authors = [{ name = "RAGUNATH R", email = "ragunathravi73@gmail.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Communications :: File Sharing",
]
keywords = ["file-transfer", "p2p", "networking", "tui", "quic", "fast-transfer"]
dependencies = [
    "tqdm",
    "colorama",
    "cryptography",
    "pyperclip",
    "pyreadline3; sys_platform == 'win32'",
]

[project.urls]
Homepage = "https://github.com/ragu-123/pyshare-cli"
Issues = "https://github.com/ragu-123/pyshare-cli/issues"

[project.scripts]
pyshare = "pyshare.main:main"