[project]
name = "zenx"
version = "0.42.1a15"
description = "mini-framework"
requires-python = ">=3.12"
dependencies = [
    "curl-cffi>=0.12.0",
    "orjson>=3.11.0",
    "parsel>=1.10.0",
    "pebble>=5.1.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "python-dotenv>=1.1.1",
    "structlog>=25.4.0",
    "typer>=0.16.0",
    "uvloop>=0.21.0",
    "httpx>=0.28.1",
    "protobuf>=6.31.1",
    "html-text>=0.7.0",
    "redis[hiredis]>=6.2.0",
    "setproctitle>=1.3.7",
    "aiofiles>=24.1.0",

    "grpcio>=1.73.1",
    "protobuf>=6.31.1",
    "psutil>=7.0.0",
    "websockets>=15.0.1",
]

[project.scripts]
zenx = "zenx.cli:app"
