[project]
name = "mascope_tools"
version = "2025.10.15"
description = "Mascope's public library, containing tools for spectra postprocessing."
classifiers = [
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
authors = [
    { name = "Oskari Kausiala", email = "oskari.kausiala@karsa.fi>" },
    { name = "Konstantin Tumashevich", email = "konstantin.tumashevich@karsa.fi>" },
    ]
maintainers = [
    { name = "Oskari Kausiala", email = "oskari.kausiala@karsa.fi>" },
    { name = "Konstantin Tumashevich", email = "konstantin.tumashevich@karsa.fi>" },
    ]
license.text = "MIT"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "isospecpy>=2.2.3",
    "mascope-sdk>=2025.10.14",
    "numpy>=1.26",
    "scipy>=1.16.1",
    "pandas>=2.3.1",
    "polars>=1.31.0",
    "pyarrow>=21.0.0",
    "pyteomics>=4.7.5",
    "tqdm>=4.67.1",
]

[project.urls]
homepage = "https://karsa.fi/"
repository = "https://github.com/Karsa-Oy/Mascope"
documentation = "https://github.com/Karsa-Oy/Mascope"
"Bug Tracker" = "https://github.com/Karsa-Oy/Mascope/issues"

[build-system]
requires = ["uv_build>=0.6,<0.7"]
build-backend = "uv_build"
