[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iugu-python-sdk"
version = "1.3.1"
description = "Client de comunicaÃ§ao c/ API da IUGU"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
authors = [
  {name = "Filipe Coelho", email = "filipe@fmconsult.com.br"},
]
keywords = ["sdk", "api", "iugu", "fmconsult"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = []

[project.urls]
"Homepage" = "https://github.com/seuuser/minha-biblioteca"
"Bug Tracker" = "https://github.com/seuuser/minha-biblioteca/issues"
