[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lcmodel_wrapper"
version = "0.1.1"
description = "Python wrapper for LCModel MRS fitting"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

authors = [
  { name = "Julian Merkofer", email = "j.p.merkofer@tue.nl" }
]

dependencies = [
  "numpy>=1.22",
  "scipy>=1.10",
  "fsl_mrs>=2.1.0"
]

[project.urls]
Homepage = "https://github.com/julianmer/PyLCModel"
Repository = "https://github.com/julianmer/PyLCModel"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
