[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zz-tools"
version = "0.2.74.post2"
description = "Small helpers for MCGT project"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "Jean-Philip Lalumi√®re" }]

[tool.setuptools]
license-files = []

[tool.setuptools.packages.find]
where = ["."]
include = ["zz_tools*"]
