[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
name = "peaks-arpes"
description = "Python tools for analysis of angle-resolved photoemission and related spectroscopic data"
readme = "README.md"
license = { file = "LICENSE.md" }
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Physics",
]
keywords = ["ARPES", "photoemission", "spectroscopy", "xarray"]
requires-python = ">=3.11,<3.14"
dependencies = [
        "ipykernel (>=6.25,<7)",
        "ipywidgets (>=8.1,<9)",
        "numpy (>=2.0,<3)",
        "matplotlib (>=3.9,<4)",
        "xarray (>=2025.6.0)",
        "pint-xarray (>=0.4,<0.5)",
        "dask[diagnostics] (>=2024.6.0)",
        "h5py (>=3.11,<4)",
        "tqdm (>=4.66,<5)",
        "natsort (>=8.4,<9)",
        "igor2 (>=0.5,<1)",
        "jupyterlab (>=4.2,<5)",
        "numbagg (>=0.8,<1)",
        "numba-progress (>=1.1,<2)",
        "numexpr (>=2.10, <3)",
        "hvplot (>=0.10,<1)",
        "pyqt6 (>=6.7,<7)",
        "pyqtgraph (>=0.13,<1)",
        "scikit-image (>=0.24,<1)",
        "pyperclip (>=1.9,<2)",
        "lmfit (>=1.3,<2)",
        "pydantic (>=2.9,<3)",
        "termcolor (>=2.5,<3)",
        "h5netcdf (>=1.4,<2)",
        "zarr (>=3.0,<4)",
        ]
dynamic = ["version"]

[[project.authors]]
name = "Phil King"
email = "pdk6@st-andrews.ac.uk"

[[project.authors]]
name = "Brendan Edwards"

[[project.authors]]
name = "Shu Mo"
email = "sm584@st-andrews.ac.uk"

[project.urls]
Source = "https://github.com/phrgab/peaks"
Issues = "https://github.com/phrgab/peaks/issues"
Documentation = "https://research.st-andrews.ac.uk/kinggroup/peaks/"

[project.optional-dependencies]
structure = [
        "ase (>3.24,<4)",
        "trimesh (>4.6,<5)",
]
ML = ["scikit-learn (>=1.3,<2)"]
docs = [
        "sphinx (>=8.2,<9)",
        "sphinx-copybutton (>=0.5,<1)",
        "sphinx-togglebutton (>=0.3,<1)",
        "sphinx-inline-tabs (>=2023)",
        "sphinx-autoapi (>=3.6,<4)",
        "myst-parser (>=4.0,<5)",
        "myst-nb (>=1.2,<2)",
        "pydata-sphinx-theme (>=0.16,<1)",
        ]
dev = ["ruff","pre-commit","nbstripout"]

[tool.ruff]
line-length = 89
target-version = "py312"
exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "I", "B"]
ignore = ["E203", "E501"]
fixable = ["I"]

[tool.flit.module]
name = "peaks"
