[project]
name = "broinsight"
version = "0.1.2"
description = "If you don't know what to do with your data, I got you, Bro!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "broflow>=0.1.5",
    "brollm>=0.1.2",
    "broprompt>=0.1.5",
    "duckdb>=1.3.2",
    "nbformat>=5.10.4",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "pydantic>=2.11.7",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "boto3>=1.40.22",
    "ipykernel>=6.30.1",
]

[tool.setuptools]
packages = ["broinsight", "broinsight.actions", "broinsight.metadata"]

[tool.setuptools.package-data]
broinsight = ["prompt_hub/*.md"]
