[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "img2term"
version = "0.1.1"
description = "Display an image in your terminal"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "Unlicense"}
authors = [
    {name = "Mike Wang", email = "mike.wang7@gmail.com"}
]
dependencies = [
    "pillow"
]

[project.urls]
Homepage = "https://github.com/myswang/img2term"
Repository = "https://github.com/myswang/img2term"

[project.scripts]
img2term = "img2term.img2term:main"